### ISSUE TITLE
why do you used ! here ?

### ISSUE THREAD

**Issue by bagratzakaryan** [mkrtchyan98/angularCourse#9]
https://github.com/mkrtchyan98/angularCourse/blob/350bdac2ec4007c0a61b0d01ee26a198fefd4aeb/src/app/todo-list/todo-list.component.ts#L19

**Comment by tigranmk** [comment]
when not putting it, typescript shows error 'Property 'todos' has no initializer and is not definitely assigned in the constructor.ts(2564)'

**Comment by tigranmk** [comment]
"strictPropertyInitialization": false
put this in tsconfig.json and the error mentioned above disappeared.
